# Generated by Django 5.1.15 on 2026-06-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('Dormitory', models.CharField(default=None, max_length=200, unique=True)),
                ('building_Information', models.CharField(max_length=400)),
                ('Bed_Service', models.CharField(max_length=100)),
                ('Toilet_Bathroom', models.CharField(max_length=100)),
                ('Accommodation_cap', models.CharField(max_length=100, null=True)),
                ('Perspective', models.TextField(null=True)),
                ('Internal_Faclities', models.TextField()),
                ('Additional_details', models.TextField(null=True)),
                ('time_reserve', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Passenger.user_home_owner')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Room_picture')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Room.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryDate', models.DateTimeField()),
                ('ReservDate', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Passenger.user_war_struck')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Room.rooms')),
            ],
        ),
    ]
