# Generated by Django 5.1.15 on 2026-07-08 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passenger', '0003_delete_hostrequest'),
        ('Room', '0002_remove_rooms_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Passenger.user_home_owner'),
        ),
    ]
