# Generated by Django 5.1.15 on 2026-06-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Passenger', '0001_initial'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allpaid', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paymentDate', models.DateField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Passenger.user_war_struck', to_field='slug')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.reservation', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='RecordReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('owner_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Passenger.user_home_owner')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Passenger.user_war_struck')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Payment.payment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.rooms')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('reservation',), name='unique_payment_per_reservation'),
        ),
    ]
