# Generated by Django 5.1.15 on 2026-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='host_requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
